# Generated by Django 4.1.7 on 2023-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_views_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="snippet",
            field=models.TextField(default="", max_length=200),
        ),
    ]
